import { Activity, PageTitle } from "@/components";
import { ActivityDto } from "@/graphql/generated/types";
import GetLatestActivities from "@/graphql/queries/activity/getLatestActivities";
import { useGlobalStyles } from "@/utils";
import { useQuery } from "@apollo/client";
import { Button, Flex, Grid, Text } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const { classes } = useGlobalStyles();
  const { data, loading: loadingMyActivities, refetch: refreshMyActivities } = useQuery(GetLatestActivities);

  const activities = data?.getLatestActivities;

  return (
    <>
      <Head>
        <title>Accueil | CDTR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageTitle title="Accueil" />
        <Text>
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem
          accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
          ab illo inventore veritatis et quasi architecto beatae vitae dicta
          sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
          aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos
          qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui
          dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed
          quia non numquam eius modi tempora incidunt ut labore et dolore magnam
          aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum
          exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
          ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in
          ea voluptate velit esse quam nihil molestiae consequatur, vel illum
          qui dolorem eum fugiat quo voluptas nulla pariatur?
        </Text>
        {activities?.length > 0 && (
          <>
            <Flex align="center" justify="space-between">
              <h2>Découvrez les dernières activités</h2>
              <Link href={`/discover`} className={classes.link}>
                <Button
                  variant="outline"
                  color="dark"
                  fullWidth
                  mt="md"
                  radius="md"
                >
                  Voir plus
                </Button>
              </Link>
            </Flex>
            {loadingMyActivities ? (
              <div>Loading my activities...</div>
            ): (
              <Grid>
              {activities.map((activity: ActivityDto) => (
                <Activity activity={activity} key={activity.id} refresh={refreshMyActivities} />
              ))}
            </Grid>
            )}
            
          </>
        )}
      </main>
    </>
  );
}
